version: '3.9'

services:
  app-dev:
    image: dev:latest # Use prebuilt image for development
    ports:
      - "8001:8001" # Expose the app on port 3030 for dev
    environment:
      NODE_ENV: development
    command: ["bun", "src/server.ts"]
    volumes:
      - .:/usr/src/app # Bind mount for live code updates
      - ./files:/usr/src/app/files # Mount the local `files` folder to `/usr/src/app/files` in the container
    networks:
      - app-network
    restart: always

  app-prd:
    image: prd:latest # Use prebuilt image for production
    ports:
      - "3030:3000" # Expose the app on a different port for production
    environment:
      NODE_ENV: production
    command: ["bun", "src/server.ts"]
    volumes:
      - ./files:/usr/src/app/files # Mount the local `files` folder to `/usr/src/app/files` in the container
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
