version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Ensure the Dockerfile is named correctly and in the root directory
    ports:
      - "3030:3030" # Expose the app on port 3000; adjust as necessary for your app's port
    environment:
      NODE_ENV: production
    command: ["bun", "src/server.ts"]
    volumes:
      - .:/usr/src/app # Optional: bind mount for live code updates
      - ./files:/usr/src/app/files # Mount the local `files` folder to `/usr/src/app/files` in the container
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
